services:
  - type: web
    name: kite-telegram-bot
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kite_telegram_bot.py"
